### ISSUE TITLE
Required SFML installation on Mac

### ISSUE THREAD

**Issue by stacksjb** [silverweed/lifish#18]
I recently downloaded the latest build on Mac OS X and it failed to run with the error
"tried: '/usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib' (no such file)"

Installing SFML using [homebrew](https://brew.sh/) with "brew install sfml" resolved the issue.

Noting for documentation purposes.

Thx!

**Comment by jackoverfull** [comment]
Actually there is no need to install anything: SFML is included, just not linked correctly.

Issuing these commands from the terminal solves the issue. You might need XCode to get install_name_tool, I'm not sure it comes with the system these days.
```
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib @rpath/sfml-graphics.framework/Versions/2.5.1/sfml-graphics /path/to/BOOM\ Remake.app/Contents/MacOS/lifish 
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib @rpath/sfml-window.framework/Versions/2.5.1/sfml-window /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-audio.2.5.dylib @rpath/sfml-audio.framework/Versions/2.5.1/sfml-audio /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib @rpath/sfml-system.framework/Versions/2.5.1/sfml-system /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
```

**Comment by stacksjb** [comment]
Thanks for the clarification. Sounds like it wasn't linked at compilation time. Worth looking into.

**Comment by silverweed** [comment]
Sorry for the delayed reply. It might be something has changed since the last time I tested the build pipeline on Mac; I create the Mac version with `makeapp_osx.sh` which is supposed to properly link the libs using `install_name_tool`, so maybe the fix is as simple as changing one line in that script. Unfortunately I cannot build/test the game on OSX anymore, so I'm afraid this would need to be handled by someone else who can do that.

**Comment by stacksjb** [comment]
I can confirm this is not an issue with the latest build/fix that @orazioedoardo makes.
