### ISSUE TITLE
Input not working properly on new OSX

### ISSUE THREAD

**Issue by silverweed** [silverweed/lifish#6]
SFML 2.4 fails to properly capture keyboard input on latest version of OSX. 
Investigate this and either make it work (probably by upgrading to 2.5) or work around the issue (key event seem to still be working).

**Comment by silverweed** [comment]
Looks like newer os versions won't even let the app run without signing, so I'm hereby dropping Apple support for lifish/BOOM remake.

**Comment by stacksjb** [comment]
It works perfectly fine for me on Catalina 10.15.2 and runs fine. 
I reject this and would recommend you continue to support it :)
Happy to assist with debugging. You have to allow event capture, since it uses global event capture, which isn't ideal but expected given the way this application is written.
<img width="672" alt="Screen Shot 2020-02-12 at 12 49 46 PM" src="https://user-images.githubusercontent.com/2865491/74362188-3f42d880-4d96-11ea-8d04-4e7828e8c1eb.png">

**Comment by silverweed** [comment]
That's an interesting turnaround: I couldn't get it working properly on the only MacBook I could test it on, but I admit not trying that thoroughly. The thing that puzzled me most is that I had to disable the security policy from the terminal, as the option disappeared from the settings.

The problem in supporting osx properly is that I don't have access to a recent Mac, so I just can't test the game every time I update it. Until I have either regular access to an Apple machine or enough time to dedicate, let's say Apple support is... not assured.
I appreciate your help and I hope I'll be able to make the game easily playable on osx sooner than later :-) (though I fear the future is grim for unsigned apps)

**Comment by MegaChriz** [comment]
Yes, please keep supporting macOS, if you can 🙂

I currently don’t own a Mac yet that can run macOS 10.15, but as soon as I do it would be cool to keep having access to this game. I don’t think that BOOM will work on the latest OS, because I believe that one is 32-bit (I’m not on my Mac right now, so cannot check).
